Map<String, String> vi = {
  "AF": "Afghanistan",
  "AX": "Quần đảo Aland",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua và Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AC": "Đảo Ascension",
  "AU": "Châu Úc",
  "AT": "Áo",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "nước Bỉ",
  "BZ": "Belize",
  "BJ": "Bén",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia và Herzegovina",
  "BW": "Botswana",
  "BR": "Brazil",
  "IO": "Lãnh thổ Ấn Độ Dương Anh",
  "VG": "Quần đảo British Virgin",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Campuchia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "BQ": "Hà Lan Caribbean",
  "KY": "Quần đảo Cayman",
  "CF": "Cộng hòa trung phi",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "Trung Quốc",
  "CX": "Đảo Giáng sinh",
  "CC": "Quần đảo Cocos [Keeling]",
  "CO": "Colombia",
  "KM": "Comoros",
  "CD": "Cộng hòa Dân chủ Congo",
  "CG": "Cộng hòa Congo",
  "CK": "Quần đảo nấu ăn",
  "CR": "Costa Rica",
  "CI": "Côte d'Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Rượu cam bì",
  "CY": "Síp",
  "CZ": "Cộng hòa Séc",
  "DK": "Đan mạch",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Cộng hòa Dominican",
  "TL": "Đông Timor",
  "EC": "Ecuador",
  "EG": "Ai Cập",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Quần đảo Falkland [Islas Malvinas]",
  "FO": "Quần đảo Faroe",
  "FJ": "Fiji",
  "FI": "Phần Lan",
  "FR": "Pháp",
  "GF": "Guiana thuộc Pháp",
  "PF": "Polynesia Pháp",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "nước Đức",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Hy Lạp",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea Conakry",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Đảo nghe và Quần đảo McDonald",
  "HN": "Honduras",
  "HK": "Hồng Kông",
  "HU": "Hungary",
  "IS": "Nước Iceland",
  "IN": "Ấn Độ",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Đảo của con người",
  "IL": "Người israel",
  "IT": "Nước Ý",
  "JM": "Jamaica",
  "JP": "Nhật Bản",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Nước Lào",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Litva",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MK": "Macedonia",
  "MG": "Madagascar",
  "MW": "Ma -rốc",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "đảo Marshall",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mông Cổ",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Ma -rốc",
  "MZ": "Mozambique",
  "MM": "Myanmar (Miến Điện]",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "nước Hà Lan",
  "NC": "Caledonia mới",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Nigeria",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Đảo Norfolk",
  "KP": "Bắc Triều Tiên",
  "MP": "Quần đảo Bắc Mariana",
  "NO": "Na Uy",
  "OM": "Ô -man",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Lãnh thổ Palestine",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Ba Lan",
  "PT": "Bồ Đào Nha",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Đoàn tụ",
  "RO": "Romania",
  "RU": "Nga",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena",
  "KN": "Kitts",
  "LC": "Thánh Lucia",
  "MF": "Saint martin",
  "PM": "Saint Pierre và Miquelon",
  "VC": "Thánh Vincent",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome và Principe",
  "SA": "Ả Rập Saudi",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Quần đảo Solomon",
  "SO": "Somalia",
  "ZA": "Nam Phi",
  "GS": "Nam Georgia và Quần đảo Nam Sandwich",
  "KR": "Hàn Quốc",
  "SS": "phía nam Sudan",
  "ES": "Tây ban nha",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard và Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Thụy Điển",
  "CH": "Thụy sĩ",
  "SY": "Syria",
  "TW": "Đài Loan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "nước Thái Lan",
  "TG": "Đi",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad & Tobago",
  "TN": "Tunisia",
  "TR": "Thổ Nhĩ Kỳ",
  "TM": "Turkmenistan",
  "TC": "Quần đảo Thổ Nhĩ Kỳ và Caicos",
  "TV": "Tuvalu",
  "VI": "Quần đảo Virgin thuộc Hoa Kỳ",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "các Tiểu Vương Quốc Ả Rập Thống Nhất",
  "GB": "Vương quốc Anh",
  "US": "Hoa Kỳ",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Thành phố Vatican",
  "VE": "Venezuela",
  "VN": "Việt Nam",
  "WF": "Wallis và Futuna",
  "WW": "Trên toàn thế giới",
  "EH": "Phía tây Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};
